# make a function for matching the string

N="TAG"
K="L"
D="E"

g4 = 'NKXD'
protein = 'MASEIHMTGPMCLIENTNGRLMANPEALKILSAITQPMVVVAIVGLYRTGKSYLMNKLAGKKKGFSLGSTVQSHTKGIWMWCVPHPKKPGHILVLLDTEGLGDVEKGDNQNDSWIFALAVLLSSTFVYNSIGTINQQAMDQLYYVTELTHRIRSKSSPDENENEVEDSADFVSFFPDFVWTLRDFSLDLEADGQPLTPDEYLTYSLKLKKGTSQKDETFNLPRLCIRKFFPKKKCFVFDRPVHRRKLAQLEKLQDEELDPEFVQQVADFCSYIFSNSKTKTLSGGIQVNGPRLESLVLTYVNAISSGDLPCMENAVLALAQIENSAAVQKAIAHYEQQMGQKVQLPTETLQELLDLHRDSEREAIEVFIRSSFKDVDHLFQKELAAQLEKKRDDFCKQNQEASSDRCSALLQVIFSPLEEEVKAGIYSKPGGYRLFVQKLQDLKKKYYEEPRKGIQAEEILQTYLKSKESMTDAILQTDQTLTEKEKEIEVERVKAESAQASAKMLQEMQRKNEQMMEQKERSYQEHLKQLTEKMENDRVQLLKEQERTLALKLQEQEQLLKEGFQKESRIMKNEIQDLQTKMRRRKACTIS'

def g4_match(g4,protein):

    N = "NTAG"
    K = "KLQ"
    D = "DE"

    spl_mismatch, mismatch = (0,0)

    for x,y in zip(g4,protein):
        print x, y
        if not (x == 'X' or y == x):
            if((x == 'T' and y in N) or (x == 'L' and y in K) or (x == 'E' and y in D)):
                spl_mismatch+=1
            else:
                mismatch+=1
    print mismatch
    print spl_mismatch
    if mismatch > 0 or spl_mismatch > 2:
        return False

    return True

print g4_match(g4,protein)
